# Generated by Django 2.2 on 2019-05-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfunc', models.IntegerField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=200)),
                ('titulacao', models.CharField(max_length=50)),
                ('fone', models.CharField(max_length=13)),
            ],
        ),
    ]
