# Generated by Django 2.2 on 2019-05-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nfunc',
            field=models.IntegerField(),
        ),
    ]
