# Generated by Django 2.2 on 2019-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0002_auto_20190528_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('titulo', models.CharField(max_length=25)),
            ],
        ),
    ]
