# Generated by Django 2.2 on 2019-05-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0003_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummat', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
