# Generated by Django 2.2 on 2019-05-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0004_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('nota_final', models.IntegerField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Disciplina')),
                ('nummat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Aluno')),
            ],
        ),
    ]
