# Generated by Django 2.2 on 2019-05-28 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0005_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('carga', models.IntegerField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Disciplina')),
                ('nfunc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculdade.Professor')),
            ],
        ),
    ]
