# Generated by Django 2.2 on 2019-06-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0006_alocacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='nummat',
            new_name='nome',
        ),
    ]
