# Generated by Django 2.2 on 2019-06-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0007_auto_20190607_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='codigo',
            new_name='titulo',
        ),
    ]
